### ISSUE TITLE
Timestamps on prices

### ISSUE THREAD

**Issue by davidkelley** [CptSpaceToaster/tcgcsv#1]
Hi, this is a fantastic piece of work and many thanks for making it publicly accessible!

Apologies in advance if this is already documented somewhere and I've missed it. Are you able to add a timestamp to the prices? Or is the timestamp implied from the time of ingestion? (20:00 UTC)

**Comment by CptSpaceToaster** [comment]
The script runs at 20:00 UTC, and over ~5 minutes, pulls _all products and all product prices_.

[last-updated.txt](https://tcgcsv.com/last-updated.txt) is a text file that's written when [the script](https://github.com/CptSpaceToaster/tcgcsv/blob/main/lambda_tcgplayer_etl/tcgplayer_etl/main.py#L330) finishes collecting and saving _all_ information!

TCGPlayer updates prices throughout the day as sales occur, so they _are_ dynamic behind the scenes. But TCGCSV only serves a cached response, and only updates once a day.

So to finally answer your question... I would just say "all prices are updated at" [last-updated.txt](https://tcgcsv.com/last-updated.txt) which is what I say on the homepage https://tcgcsv.com
<img width="435" alt="Image" src="https://github.com/user-attachments/assets/2e0287b8-5f9e-4a57-b3f4-24d1df0cbe0a" />

Does that answer your question?

**Comment by davidkelley** [comment]
Hi there,

Thanks for the speedy response!

It absolutely does, many thanks for clarifying.
